export const CHECK_REGISTER_USER_REQUEST = "CHECK_REGISTER_USER_REQUEST";
export const CHECK_REGISTER_USER_SUCCESS = "CHECK_REGISTER_USER_SUCCESS";
export const CHECK_REGISTER_USER_ERROR = "CHECK_REGISTER_USER_ERROR";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
